### ISSUE TITLE
When will this mod be updated?

### ISSUE THREAD

**Issue by ponyzerteal** [VincentVision/BetterTownOfUs#1]

**Comment by VincentVision** [comment]
Hello, sorry, I work rarely on this mod.
somes releases was share on the discord and i load the last release now if your are interested again

**Comment by ponyzerteal** [comment]
Wow, I'm surprised that my favorite module can be updated suddenly, but the tou-r I'm playing now is a version modified by others around. This modified version contains roles that have been deleted, so could you please add the roles deleted by tou-r to B-TOR?
What we miss most is shifter and camouflager, which have the greatest influence on the deleted roles.

**Comment by VincentVision** [comment]
Yeah is onproject for shifter, i can add camouflager too

**Comment by ponyzerteal** [comment]
OK, in addition, can you provide json files for translation, and can I translate the contents into Chinese?




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年8月15日(星期一) 晚上6:08
收件人: ***@***.***&gt;; 
抄送: "GMH ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [VincentVision/BetterTownOfUs] When will this mod be updated? (Issue #1)





 
Yeah is onproject for shifter, i can add camouflager too

**Comment by ponyzerteal** [comment]
OK, in addition, can you provide json files for translation, and can I translate the contents into Chinese?
